"""initial

Revision ID: 0c3ac4dd9a0e
Revises: 
Create Date: 2026-05-29 09:17:05.708873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c3ac4dd9a0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('ganaderias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animales',
    sa.Column('crotal', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('macho', 'hembra', name='sexo_animal'), nullable=False),
    sa.Column('rol', sa.Enum('madre', 'padre', 'recria', name='rol_animal'), nullable=False),
    sa.Column('composicion_racial', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raza_texto', sa.String(length=300), nullable=True),
    sa.Column('padre_crotal', sa.String(length=20), nullable=True),
    sa.Column('padre_desc', sa.String(length=300), nullable=True),
    sa.Column('madre_crotal', sa.String(length=20), nullable=True),
    sa.Column('ganaderia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ganaderia_id'], ['ganaderias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('crotal')
    )
    op.create_index(op.f('ix_animales_ganaderia_id'), 'animales', ['ganaderia_id'], unique=False)
    op.create_index(op.f('ix_animales_madre_crotal'), 'animales', ['madre_crotal'], unique=False)
    op.create_index(op.f('ix_animales_padre_crotal'), 'animales', ['padre_crotal'], unique=False)
    op.create_table('animales_historial',
    sa.Column('crotal', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('macho', 'hembra', name='sexo_animal'), nullable=False),
    sa.Column('rol', sa.Enum('madre', 'padre', 'recria', name='rol_animal'), nullable=False),
    sa.Column('composicion_racial', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raza_texto', sa.String(length=300), nullable=True),
    sa.Column('padre_crotal', sa.String(length=20), nullable=True),
    sa.Column('padre_desc', sa.String(length=300), nullable=True),
    sa.Column('madre_crotal', sa.String(length=20), nullable=True),
    sa.Column('ganaderia_id', sa.Integer(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=False),
    sa.Column('motivo_salida', sa.Enum('venta', 'muerte_natural', 'depredador', 'sacrificio', 'cesion', name='motivo_salida'), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comprador', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ganaderia_id'], ['ganaderias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('crotal')
    )
    op.create_index(op.f('ix_animales_historial_ganaderia_id'), 'animales_historial', ['ganaderia_id'], unique=False)
    op.create_table('ganaderia_usuarios',
    sa.Column('ganaderia_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'colaborador', name='rol_usuario'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ganaderia_id'], ['ganaderias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ganaderia_id', 'usuario_id'),
    sa.UniqueConstraint('ganaderia_id', 'usuario_id', name='uq_ganaderia_usuario')
    )
    op.create_table('invitaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ganaderia_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'revocada', name='estado_invitacion'), nullable=False),
    sa.Column('creada_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creada_by'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ganaderia_id'], ['ganaderias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitaciones_token'), 'invitaciones', ['token'], unique=True)
    op.create_table('nacimientos_anio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_exacta', sa.Date(), nullable=True),
    sa.Column('crotal_animal', sa.String(length=20), nullable=False),
    sa.Column('crotal_madre', sa.String(length=20), nullable=False),
    sa.Column('crotal_padre', sa.String(length=20), nullable=True),
    sa.Column('padre_desc', sa.String(length=300), nullable=True),
    sa.Column('ganaderia_id', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('anio >= 2000 AND anio <= 2100', name='ck_nacimiento_anio_rango'),
    sa.ForeignKeyConstraint(['ganaderia_id'], ['ganaderias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nacimientos_anio_anio'), 'nacimientos_anio', ['anio'], unique=False)
    op.create_index(op.f('ix_nacimientos_anio_crotal_animal'), 'nacimientos_anio', ['crotal_animal'], unique=False)
    op.create_index(op.f('ix_nacimientos_anio_crotal_madre'), 'nacimientos_anio', ['crotal_madre'], unique=False)
    op.create_index(op.f('ix_nacimientos_anio_crotal_padre'), 'nacimientos_anio', ['crotal_padre'], unique=False)
    op.create_index(op.f('ix_nacimientos_anio_ganaderia_id'), 'nacimientos_anio', ['ganaderia_id'], unique=False)
    op.create_table('ventas_anio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_exacta', sa.Date(), nullable=True),
    sa.Column('crotal_animal', sa.String(length=20), nullable=False),
    sa.Column('ganaderia_id', sa.Integer(), nullable=False),
    sa.Column('comprador', sa.String(length=200), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('anio >= 2000 AND anio <= 2100', name='ck_venta_anio_rango'),
    sa.ForeignKeyConstraint(['ganaderia_id'], ['ganaderias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_anio_anio'), 'ventas_anio', ['anio'], unique=False)
    op.create_index(op.f('ix_ventas_anio_crotal_animal'), 'ventas_anio', ['crotal_animal'], unique=False)
    op.create_index(op.f('ix_ventas_anio_ganaderia_id'), 'ventas_anio', ['ganaderia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_anio_ganaderia_id'), table_name='ventas_anio')
    op.drop_index(op.f('ix_ventas_anio_crotal_animal'), table_name='ventas_anio')
    op.drop_index(op.f('ix_ventas_anio_anio'), table_name='ventas_anio')
    op.drop_table('ventas_anio')
    op.drop_index(op.f('ix_nacimientos_anio_ganaderia_id'), table_name='nacimientos_anio')
    op.drop_index(op.f('ix_nacimientos_anio_crotal_padre'), table_name='nacimientos_anio')
    op.drop_index(op.f('ix_nacimientos_anio_crotal_madre'), table_name='nacimientos_anio')
    op.drop_index(op.f('ix_nacimientos_anio_crotal_animal'), table_name='nacimientos_anio')
    op.drop_index(op.f('ix_nacimientos_anio_anio'), table_name='nacimientos_anio')
    op.drop_table('nacimientos_anio')
    op.drop_index(op.f('ix_invitaciones_token'), table_name='invitaciones')
    op.drop_table('invitaciones')
    op.drop_table('ganaderia_usuarios')
    op.drop_index(op.f('ix_animales_historial_ganaderia_id'), table_name='animales_historial')
    op.drop_table('animales_historial')
    op.drop_index(op.f('ix_animales_padre_crotal'), table_name='animales')
    op.drop_index(op.f('ix_animales_madre_crotal'), table_name='animales')
    op.drop_index(op.f('ix_animales_ganaderia_id'), table_name='animales')
    op.drop_table('animales')
    op.drop_table('ganaderias')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
